name: places
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^0.19.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - res/
    - res/images/icons/Search.svg
    - res/images/icons/Filter.svg
    - res/images/icons/Plus.svg
    - res/images/icons/Settings-fill.svg
    - res/images/icons/Settings.svg
    - res/images/icons/Map.svg
    - res/images/icons/List.svg
    - res/images/icons/Heart.svg
    - res/images/icons/Clear.svg
    - res/images/icons/Delete.svg
    - res/images/icons/Hotel.svg
    - res/images/icons/Restourant.svg
    - res/images/icons/Info.svg
    - res/images/icons/Particular place.svg
    - res/images/icons/Park.svg
    - res/images/icons/Museum.svg
    - res/images/icons/Cafe.svg
    - res/images/icons/GO.svg
    - res/images/icons/Arrow Left.svg
    - res/images/icons/Arrow Right.svg
    - res/images/icons/Calendar.svg
    - res/images/icons/Close.svg
    - res/images/icons/Share.svg
    - res/images/icons/Card.svg
    - res/images/icons/Bucket.svg
    - res/images/icons/Camera.svg
    - res/images/icons/Photo.svg
    - res/images/icons/File.svg
    - res/images/mock_images/eiffel.jpeg
    - res/images/onboarding_icons/tutorial_1.svg
    - res/images/onboarding_icons/tutorial_2.svg
    - res/images/onboarding_icons/tutorial_3.svg
  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: res/fonts/Roboto/Roboto-Black.ttf
          weight: 900
        - asset: res/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: res/fonts/Roboto/Roboto-Medium.ttf
          weight: 500

